FROM registry.gitlab.com/pingu8007/devcontainer/main:jdk-25

# FROM registry.gitlab.com/pingu8007/devcontainer/main:jdk-8

# FROM registry.gitlab.com/pingu8007/devcontainer/main:base
# RUN asdf plugin add golang && asdf install golang latest:1.26.1
