volumes:
  postgres-data:
  mariadb-data:

services:
  adminer:
    image: adminer
    # ports:
    #   - 8080:8080
    restart: unless-stopped

  postgres:
    image: postgres:17-alpine
    # ports:
    #   - 5432:5432
    restart: unless-stopped
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    # volumes:
    #   - postgres-data:/var/lib/postgresql/data

  mariadb:
    image: mariadb:lts
    # ports:
    #   - 3306:3306
    restart: unless-stopped
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    # volumes:
    #   - mariadb-data:/var/lib/mysql

  redis:
    image: redis:alpine
    # ports:
    #   - 6379:6379
    restart: unless-stopped

  plantuml:
    image: plantuml/plantuml-server:jetty
    # ports:
    #   - 9999:8080
    restart: unless-stopped
    environment:
      - BASE_URL
      - PLANTUML_LIMIT_SIZE
      - PLANTUML_STATS
      - HTTP_AUTHORIZATION
      - ALLOW_PLANTUML_INCLUDE

# visit https://gitlab.com/pingu8007/devcontainer for more example
