volumes:
  asdf-data:

services:
  workspace:
    build:
      context: .
      dockerfile: Dockerfile
    user: user
    command: sleep infinity
    restart: unless-stopped
    volumes:
      - ..:/workspaces
      - /var/run/docker.sock:/var/run/docker.sock
      - asdf-data:/userdata/asdf
